### ISSUE TITLE
kafka mqtt connector is not able to resume connection with mqtt broker when it is lost

### ISSUE THREAD

**Issue by eugpermar** [wizzie-io/prozzie#82]
# what is happening.
kafka mqtt connector is not able to resume connection with mqtt broker when it is lost

# Steps to reproduce the problem. Is always reproducible?
-
# Observed behavior
-
# Expected behavior and why
-
# Name and version of OS
CentOS 7
# Related configuration files used
-

Attached trace:
```
[2018-08-18 06:24:04,498] ERROR MQTT connection lost! (com.evokly.kafka.connect.mqtt.MqttSourceConnector)
Connection lost (32109) - java.io.EOFException
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:267)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
    ... 1 more
[2018-08-18 06:24:04,498] ERROR MQTT connection lost! (com.evokly.kafka.connect.mqtt.MqttSourceConnector)
Connection lost (32109) - java.io.EOFException
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readByte(DataInputStream.java:267)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
    ... 1 more
[2018-08-18 06:24:16,097] INFO Finished WorkerSourceTask{id=cmx01-0} commitOffsets successfully in 2 ms (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2018-08-27 08:09:18,738] INFO 172.18.0.11 - - [27/Aug/2018:08:09:18 +0000] "GET /connectors/cmx01 HTTP/1.1" 200 627  267 (org.apache.kafka.connect.runtime.rest.RestServer)
```

But mqtt messages are not resumed

**Comment by eugpermar** [comment]
Fixed with #91
